version: '2.4'

networks:
  # Required for the devcontainer
  sindit_network:
    name: sindit_network

services:
  sindit_influx_db:
    extends:
      file: docker-compose.yml
      service: sindit_influx_db
    mem_limit: 500M

  sindit_neo4j_kg:
    extends:
      file: docker-compose.yml
      service: sindit_neo4j_kg

    mem_limit: 2G

  sindit_minio_s3:
    extends:
      file: docker-compose.yml
      service: sindit_minio_s3

    mem_limit: 500M

  sindit_dt_backend:
    extends:
      file: docker-compose.yml
      service: sindit_dt_backend

    mem_limit: 1G

  sindit_dt_frontend:
    extends:
      file: docker-compose.yml
      service: sindit_dt_frontend

    mem_limit: 1500M
    entrypoint: gunicorn dt_frontend:server -b :8050 --timeout 1800 --workers 1

volumes:
  sindit-minio-s3-volume:
  sindit-neo4j-conf-volume:
  sindit-neo4j-logs-volume:
  sindit-neo4j-data-volume:
  sindit-influx-db-data-volume:
  sindit-influx-db-config-volume:
