version: '2.4'

networks:
  # Required for the devcontainer
  sindit_network:
    name: sindit_network

services:
  sindit_influx_db:
    extends:
      file: docker-compose.databases.yml
      service: sindit_influx_db
    networks:
      - sindit_network
    ports:
      - '8087:8086'

  sindit_neo4j_kg:
    extends:
      file: docker-compose.databases.yml
      service: sindit_neo4j_kg
    networks:
      - sindit_network
    ports:
      - 7475:7474
      - 7688:7687

  sindit_minio_s3:
    extends:
      file: docker-compose.databases.yml
      service: sindit_minio_s3
    networks:
      - sindit_network
    ports:
      - "9000:9000"
      - "9097:9099"

  sindit_dt_backend:
    image: ghcr.io/sintef-9012/sindit:latest
    hostname: sindit-dt-backend
    container_name: sindit_dt_backend
    mem_limit: 2G
    env_file:
      - "environment_and_configuration/deployment_environment_backend.env"
    ports:
      - 8000:8000
    networks:
      - sindit_network
    depends_on:
      sindit_influx_db:
        condition: service_healthy
      sindit_neo4j_kg:
        condition: service_healthy
    healthcheck:
      test: curl localhost:8000/status
      interval: 30s
      timeout: 60s
      retries: 500
    entrypoint: python dt_backend.py
    extra_hosts:
      - "host.docker.internal:host-gateway"

  sindit_dt_frontend:
    image: ghcr.io/sintef-9012/sindit:latest
    hostname: sindit-dt-frontend
    container_name: sindit_dt_frontend
    mem_limit: 2G
    env_file:
      - "environment_and_configuration/deployment_environment_frontend.env"
    ports:
      - 8050:8050
    networks:
      - sindit_network
    depends_on:
      sindit_influx_db:
        condition: service_healthy
      sindit_neo4j_kg:
        condition: service_healthy
      sindit_dt_backend:
        condition: service_healthy
    healthcheck:
      test: curl localhost:8050
      interval: 30s
      timeout: 60s
      retries: 500
    entrypoint: gunicorn dt_frontend:server -b :8050 --timeout 1800 --workers 4

volumes:
  sindit-minio-s3-volume:
  sindit-neo4j-conf-volume:
  sindit-neo4j-logs-volume:
  sindit-neo4j-data-volume:
  sindit-influx-db-data-volume:
  sindit-influx-db-config-volume:
