version: '2.4'

networks:
  # Required for the devcontainer
  sindit_devcontainer_network:
    name: sindit_devcontainer_network

services:
  sindit_influx_db_devcontainer:
    extends:
      file: docker-compose.databases.yml
      service: sindit_influx_db
    networks:
      - sindit_devcontainer_network

    hostname: sindit-influx-db-devcontainer
    container_name: sindit_influx_db_devcontainer
    mem_limit: 1G
    ports:
      - '8086:8086'
    volumes:
      - sindit-devcontainer-influx-db-data-volume:/var/lib/influxdb2
      - sindit-devcontainer-influx-db-config-volume:/etc/influxdb2

  sindit_neo4j_kg_devcontainer:
    extends:
      file: docker-compose.databases.yml
      service: sindit_neo4j_kg
    networks:
      - sindit_devcontainer_network

    hostname: sindit-neo4j-kg-devcontainer
    container_name: sindit_neo4j_kg_devcontainer
    mem_limit: 4G
    ports:
      - 7476:7474
      - 7689:7687
    volumes:
      - sindit-devcontainer-neo4j-conf-volume:/var/lib/neo4j/conf/
      - sindit-devcontainer-neo4j-logs-volumes:/logs
      - sindit-devcontainer-neo4j-data-volume:/data

  sindit_minio_s3_devcontainer:
    extends:
      file: docker-compose.databases.yml
      service: sindit_minio_s3
    networks:
      - sindit_devcontainer_network

    hostname: sindit-minio-s3-devcontainer
    container_name: sindit_minio_s3_devcontainer
    mem_limit: 1G
    ports:
      - "9001:9000"
      - "9098:9099"
    volumes:
      - sindit-devcontainer-minio-s3-volume:/data

volumes:
  sindit-devcontainer-minio-s3-volume:
  sindit-devcontainer-neo4j-conf-volume:
  sindit-devcontainer-neo4j-logs-volume:
  sindit-devcontainer-neo4j-data-volume:
  sindit-devcontainer-influx-db-data-volume:
  sindit-devcontainer-influx-db-config-volume:
