version: '2.4'

networks:
  # Required for the devcontainer
  sindit_devcontainer_network:
    name: sindit_devcontainer_network

services:
  sindit_influx_db_devcontainer:
    extends:
      file: docker-compose.dev.yml
      service: sindit_influx_db
    mem_limit: 500M

  sindit_neo4j_kg_devcontainer:
    extends:
      file: docker-compose.dev.yml
      service: sindit_neo4j_kg
    mem_limit: 2G

  sindit_minio_s3_devcontainer:
    extends:
      file: docker-compose.dev.yml
      service: sindit_minio_s3
    mem_limit: 500M
