{{- $fullName := include "sindit.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "sindit.labels" . | nindent 4 }}
data:
  neo4j-db-password: {{ (index .Values "neo4j-standalone").neo4j.password | toString | b64enc | quote }}
  influx-db-token: {{ .Values.influxdb.auth.admin.token | toString | b64enc | quote }}
  minio-s3-password: {{ .Values.minio.auth.rootPassword | toString | b64enc | quote }}
type: Opaque
