apiVersion: v1
kind: Service
metadata:
  name: {{ include "sindit.fullname" . }}-frontend
  labels:
    {{- include "sindit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceFrontend.type }}
  ports:
    - port: {{ .Values.serviceFrontend.port }}
      targetPort: frontend
      protocol: TCP
      name: frontend
  selector:
    {{- include "sindit.selectorLabels" . | nindent 4 }}
    type: frontend
