apiVersion: v1
kind: Service
metadata:
  name: {{ include "sindit.fullname" . }}-backend
  labels:
    {{- include "sindit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.serviceBackend.type }}
  ports:
    - port: {{ .Values.serviceBackend.port }}
      targetPort: backend
      protocol: TCP
      name: backend
  selector:
    {{- include "sindit.selectorLabels" . | nindent 4 }}
    type: backend